agil_forum_homepage:
    path:     /
    defaults: { _controller: AGILForumBundle:Default:index }


agil_forum_subjects_list:
    path:     /categories/{idCategory}
    defaults: { _controller: AGILForumBundle:Categories:subjects }
    requirements:
        idCategory: \d+

agil_forum_subject_answers:
    path:     /categories/{idCategory}/{idSubject}
    defaults: { _controller: AGILForumBundle:Answers:answers }
    requirements:
        idCategory: \d+
        idSubject: \d+

agil_forum_subject_add:
    path:   /categories/{idCategory}/newPost
    defaults:
         _controller: AGILForumBundle:Subjects:subjectsAdd
    requirements:
            idCategory: \d+