agil_forum_homepage:
    path:     /
    defaults: { _controller: AGILForumBundle:Default:index }


agil_forum_subjects_list:
    path:     /categories/{idCategory}/page/{page}
    defaults:
        _controller: AGILForumBundle:Categories:subjects
        page:  1
    requirements:
        idCategory: \d+
        page : \d+


agil_forum_subject_answers:
    path:     /categories/{idCategory}/subject/{idSubject}/page/{page}
    defaults:
        _controller: AGILForumBundle:Answers:answers
        page:  1
    requirements:
        idCategory: \d+
        idSubject: \d+
        page : \d+

agil_forum_subject_add:
    path:   /categories/{idCategory}/newSubject
    defaults:
        _controller: AGILForumBundle:Subjects:subjectAdd
    requirements:
        idCategory: \d+


agil_forum_subject_to_resolve:
    path:   /categories/{idCategory}/resolveSubject/{idSubject}
    defaults:
        _controller: AGILForumBundle:Subjects:subjectResolved
    requirements:
        idCategory: \d+
        idSubject: \d+

agil_forum_subject_delete:
    path:   /categories/{idCategory}/deleteSubject/{idSubject}
    defaults:
        _controller: AGILForumBundle:Subjects:subjectDelete
    requirements:
        idCategory: \d+
        idSubject: \d+

agil_forum_answers_edit:
    path:   /categories/{idCategory}/subject/{idSubject}/edit/{idAnswer}
    defaults:
        _controller: AGILForumBundle:Answers:answersEdit
    requirements:
        idCategory: \d+
        idSubject: \d+
        idAnswer: \d+

agil_forum_answers_delete:
    path:   /categories/{idCategory}/subject/{idSubject}/delete/{idAnswer}
    defaults:
        _controller: AGILForumBundle:Answers:answersDelete
    requirements:
        idCategory: \d+
        idSubject: \d+
        idAnswer: \d+