agil_forum_homepage:
    path:     /
    defaults: { _controller: AGILForumBundle:Default:index }


agil_forum_subjects_list:
    path:     /categories/{idCategory}/page/{page}
    defaults:
        _controller: AGILForumBundle:Categories:subjects
        page:  1
    requirements:
        idCategory: \d+
        page : \d+


agil_forum_subject_answers:
    path:     /categories/{idCategory}/subject/{idSubject}/page/{page}
    defaults:
        _controller: AGILForumBundle:Answers:answers
        page:  1
    requirements:
        idCategory: \d+
        idSubject: \d+
        page : \d+

agil_forum_subject_add:
    path:   /categories/{idCategory}/newPost
    defaults:
         _controller: AGILForumBundle:Subjects:subjectsAdd
    requirements:
            idCategory: \d+