language: php

services:
  - mysql

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION="2.8.*" DB=mysql

before_script:
  - mysql -u root -e 'CREATE DATABASE amicale;'
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update
  - composer update
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load -n

script:
  - phpunit -c app src/

notifications:
  email:
    - yoann.fleury@yahoo.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c076d90da5e01680fedf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always