agil_admin_homepage:
    path:     /admin
    defaults: { _controller: AGILAdminBundle:Default:admin }

agil_admin_user:
    path:     /admin/user/{page}
    defaults:
        _controller: AGILAdminBundle:User:adminUser
        page:  1
    requirements:
            page: \d+

agil_admin_user_up:
    path:     /admin/user/up/{id}
    defaults:
        _controller: AGILAdminBundle:User:adminUserUp
    requirements:
            id: \d+

agil_admin_user_down:
    path:     /admin/user/down/{id}
    defaults:
        _controller: AGILAdminBundle:User:adminUserDown
    requirements:
            id: \d+

agil_admin_user_delete:
    path:     /admin/user/delete/{id}
    defaults:
        _controller: AGILAdminBundle:User:adminUserDelete
    requirements:
            page: \d+

agil_admin_user_add:
    path:     /admin/user/add
    defaults:
        _controller: AGILAdminBundle:User:adminUserAdd