agil_admin_homepage:
    path:     /admin
    defaults:
        _controller: AGILAdminBundle:Default:admin

agil_admin_user:
    path:     /admin/user/page/{page}
    defaults:
        _controller: AGILAdminBundle:User:adminUser
        page:  1
    requirements:
            page: \d+

agil_admin_user_up:
    path:     /admin/user/up/{id}
    defaults:
        _controller: AGILAdminBundle:User:adminUserUp
    requirements:
            id: \d+

agil_admin_user_down:
    path:     /admin/user/down/{id}
    defaults:
        _controller: AGILAdminBundle:User:adminUserDown
    requirements:
            id: \d+

agil_admin_user_delete:
    path:     /admin/user/delete/{id}
    defaults:
        _controller: AGILAdminBundle:User:adminUserDelete
    requirements:
            page: \d+

agil_admin_user_add:
    path:     /admin/user/add
    defaults:
        _controller: AGILAdminBundle:User:adminUserAdd

agil_admin_forum_categories:
    path:     /admin/forum/categories/
    defaults:
        _controller: AGILAdminBundle:Forum:adminForumCategories

agil_admin_forum_category_edit:
    path:     /admin/forum/categories/edit/{idCategory}
    defaults:
        _controller: AGILAdminBundle:Forum:adminForumCategoryEdit
    requirements:
            idCategory: \d+

agil_admin_forum_category_delete:
    path:     /admin/forum/categories/delete/{idCategory}
    defaults:
        _controller: AGILAdminBundle:Forum:adminForumCategoryDelete
    requirements:
            idCategory: \d+

# //----------------------- Logs routing ----------------------------------------------

agil_admin_logs_offer:
    path:     /admin/logs/offer
    defaults:
        _controller: AGILAdminBundle:Logs:offer

agil_admin_logs_profile:
    path:     /admin/logs/profile
    defaults:
        _controller: AGILAdminBundle:Logs:profile

agil_admin_logs_chat:
    path:     /admin/logs/chat
    defaults:
        _controller: AGILAdminBundle:Logs:chat

agil_admin_logs_forum:
    path:     /admin/logs/forum
    defaults:
        _controller: AGILAdminBundle:Logs:forum

agil_admin_logs_search:
    path:     /admin/logs/search
    defaults:
        _controller: AGILAdminBundle:Logs:search

agil_admin_logs_hall:
    path:     /admin/logs/hall
    defaults:
        _controller: AGILAdminBundle:Logs:hall