agil_admin_homepage:
    path:     /admin
    defaults: { _controller: AGILAdminBundle:Default:admin }

agil_admin_user:
    path:     /admin/user/page/{page}
    defaults:
        _controller: AGILAdminBundle:User:adminUser
        page:  1
    requirements:
            page: \d+

agil_admin_user_up:
    path:     /admin/user/up/{id}
    defaults:
        _controller: AGILAdminBundle:User:adminUserUp
    requirements:
            id: \d+

agil_admin_user_down:
    path:     /admin/user/down/{id}
    defaults:
        _controller: AGILAdminBundle:User:adminUserDown
    requirements:
            id: \d+

agil_admin_user_delete:
    path:     /admin/user/delete/{id}
    defaults:
        _controller: AGILAdminBundle:User:adminUserDelete
    requirements:
            page: \d+

agil_admin_user_add:
    path:     /admin/user/add
    defaults:
        _controller: AGILAdminBundle:User:adminUserAdd

agil_admin_forum_categories:
    path:     /admin/forum/categories/
    defaults: { _controller: AGILAdminBundle:Forum:adminForumCategories }

agil_admin_forum_category_edit:
    path:     /admin/forum/categories/edit/{idCategory}
    defaults: { _controller: AGILAdminBundle:Forum:adminForumCategoryEdit }
    requirements:
            idCategory: \d+

agil_admin_forum_category_delete:
    path:     /admin/forum/categories/delete/{idCategory}
    defaults: { _controller: AGILAdminBundle:Forum:adminForumCategoryDelete }
    requirements:
            idCategory: \d+

# admin event routing
agil_admin_events:
    path:     /admin/hall/events
    defaults: { _controller: AGILAdminBundle:Event:adminEvent }

agil_admin_event_add:
    path:     /admin/hall/event/add
    defaults: { _controller: AGILAdminBundle:Event:adminEventAdd }

agil_admin_event_edit:
    path:     /admin/hall/event/edit/{idEvent}
    defaults: { _controller: AGILAdminBundle:Event:adminEventEdit }
    requirements:
        idEvent: \d+

agil_admin_event_delete:
    path:     /admin/hall/event/delete/{idEvent}
    defaults: { _controller: AGILAdminBundle:Event:adminEventAdd }
    requirements:
        idEvent: \d+