agil_chat_homepage:
    path:     /
    defaults:
        _controller: AGILChatBundle:Default:index

agil_chat_room:
    path:     /{roomId}
    defaults:
        _controller: AGILChatBundle:Default:chatLive
    requirements:
        roomId: \d+

agil_chat_user:
    path:     /user
    defaults:
        _controller: AGILChatBundle:Default:getUserById
    methods: [POST]

agil_chat_users:
    path:     /users
    defaults:
        _controller: AGILChatBundle:Default:getUsersById
    methods: [POST]