services:
    agil_hello.topic_sample_service:
        class: AGIL\ChatBundle\Topic\AgilTopic
        arguments: ["@gos_web_socket.websocket.client_manipulator"]
        tags:
            - { name: gos_web_socket.topic }

    agil_hello.rpc_sample_service:
        class: AGIL\ChatBundle\Rpc\AgilRpc
        tags:
            - { name: gos_web_socket.rpc }