# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:
        ROLE_MODERATOR:   ROLE_USER
        ROLE_ADMIN:       ROLE_MODERATOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        main:
            pattern:   ^/
            anonymous: true
            provider:  fos_userbundle
            logout: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /login
            remember_me:
                secret:    %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        - { path: ^/search, roles: ROLE_USER }
        - { path: ^/profile/edit, roles: ROLE_USER }
        - { path: ^/offer/page$, roles: ROLE_USER } # le '$' qui restreint la route a /offer (par défaut /offer/*)
        - { path: ^/offer/add, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/chat, roles: ROLE_USER }
        - { path: ^/forum, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/hall/event/add, roles: ROLE_ADMIN }
