# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    fos_user.doctrine_registry:
            alias: doctrine

    app.form.registration:
        class: AGIL\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: agil_user_registration }

    app.form.registration:
            class: AGIL\UserBundle\Form\ResettingFormType
            tags:
                - { name: form.type, alias: agil_user_resetting }

    fos_user.mailer.twig_swift:
        class: AGIL\UserBundle\Mailer\TwigSwiftMailer
        arguments:
            - "@mailer"
            - "@router"
            - "@twig"
            - { template: { confirmation: %fos_user.registration.confirmation.template%, resetting: %fos_user.resetting.email.template% }, from_email: { confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email% } }

    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    # Format personnalisé pour le Logger de Monolog
    service.logger_formatter:
                class:     Monolog\Formatter\LineFormatter
                arguments: ["[%%datetime%%] %%message%% \n",null,false,true]

    # Logger Offer
    service_offer.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@service_offer.logger_handler]]
    # Logger Handler Offer
    service_offer.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/logsOffer.log, 200]
        calls:
            - [setFormatter, [@service.logger_formatter]]

    # Logger Forum
    service_forum.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@service_forum.logger_handler]]
    # Logger Handler Forum
    service_forum.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/logsForum.log, 200]
        calls:
            - [setFormatter, [@service.logger_formatter]]

    # Logger Profile
    service_profile.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@service_profile.logger_handler]]
    # Logger Handler Profile
    service_profile.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/logsProfile.log, 200]
        calls:
            - [setFormatter, [@service.logger_formatter]]

    # Logger Chat
    service_chat.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@service_chat.logger_handler]]
    # Logger Handler Chat
    service_chat.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/logsChat.log, 200]
        calls:
            - [setFormatter, [@service.logger_formatter]]

    # Logger Search
    service_search.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@service_search.logger_handler]]
    # Logger Handler Search
    service_search.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/logsSearch.log, 200]
        calls:
            - [setFormatter, [@service.logger_formatter]]

    # Logger Hall
    service_hall.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@service_hall.logger_handler]]
    # Logger Handler Hall
    service_hall.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/logsHall.log, 200]
        calls:
            - [setFormatter, [@service.logger_formatter]]


