agil_hall_homepage:
    path:     /hall
    defaults: { _controller: AGILHallBundle:Default:index }

agil_hall_page:
    path: hall/page/{idPage}
    defaults: { _controller: AGILHallBundle:Default:renderPage, idPage: 1 }
    requirements:
        idPage: \d+

agil_hall_event:
    path: hall/event/{idEvent}
    defaults: { _controller: AGILHallBundle:Default:event }
    requirements:
        idEvent: \d+

agil_hall_event_photos:
    path: hall/event/{idEvent}/photos
    defaults: { _controller: AGILHallBundle:Default:photosEvent }
    requirements:
        idEvent: \d+

agil_hall_event_videos:
    path: /event/{idEvent}/videos
    defaults: { _controller: AGILHallBundle:Default:videosEvent }
    requirements:
        idEvent: \d+