agil_hall_homepage:
    path:     /
    defaults: { _controller: AGILHallBundle:Default:index }

agil_hall_page:
    path: /page/{idPage}
    defaults: { _controller: AGILHallBundle:Default:renderPage, idPage: 1 }
    requirements:
        idPage: \d+

agil_hall_event:
    path: /event/{idEvent}
    defaults: { _controller: AGILHallBundle:Default:event }
    requirements:
        idEvent: \d+

agil_event_add:
    path: event/{idEvent}/add
    defaults: { _controller: AGILHallBundle:Default:eventAdd }
    requirements:
        idEvent: \d+

agil_event_edit:
    path: event/{idEvent}/edit
    defaults: { _controller: AGILHallBundle:Default:eventEdit }
    requirements:
        idEvent: \d+

agil_hall_event_photos:
    path: /event/{idEvent}/photos
    defaults: { _controller: AGILHallBundle:Default:photosEvent }
    requirements:
        idEvent: \d+

agil_hall_event_videos:
    path: event/{idEvent}/videos
    defaults: { _controller: AGILHallBundle:Default:videosEvent }
    requirements:
        idEvent: \d+

agil_hall_event_add:
    path: /event/add
    defaults: { _controller: AGILHallBundle:Default:eventAdd }

agil_hall_event_edit:
    path: /event/{idEvent}/edit
    defaults: { _controller: AGILHallBundle:Default:eventEdit }
    requirements:
        idEvent: \d+