agil_hall_homepage:
    path:     /hall
    defaults: { _controller: AGILHallBundle:Default:index }

agil_hall_calendar:
        path:     /calendar/
        defaults: { _controller: AGILHallBundle:Calendar:showCalendar }

agil_hall_calendar_data:
        path:     /calendar/data
        defaults: { _controller: AGILHallBundle:Calendar:getCalendarData }
        methods: [post]