agil_hall_homepage:
    path:     /page/{page}
    defaults:
        _controller: AGILHallBundle:Default:index
        page:  1
    requirements:
        page : \d+

agil_hall_event:
    path: /event/{idEvent}
    defaults:
        _controller: AGILHallBundle:Default:event
    requirements:
        idEvent: \d+

agil_hall_calendar:
    path:     /calendar/
    defaults:
        _controller: AGILHallBundle:Calendar:showCalendar

agil_hall_calendar_data:
    path:     /calendar/data
    defaults:
        _controller: AGILHallBundle:Calendar:getCalendarData
    methods: [post]

# Managing events

agil_hall_event_add:
    path: /event/add
    defaults: { _controller: AGILHallBundle:Event:eventAdd }

agil_hall_event_edit:
    path: /event/{idEvent}/edit
    defaults: { _controller: AGILHallBundle:Event:eventEdit }
    requirements:
        idEvent: \d+

agil_hall_event_delete:
    path:     /event/{idEvent}/delete
    defaults: { _controller: AGILHallBundle:Event:eventDelete }
    requirements:
        idEvent: \d+

