#agil_profile_homepage:
#    path:     /
#    defaults: { _controller: AGILProfileBundle:Default:index }

agil_profile:
    path:     /profil
    defaults: { _controller: AGILProfileBundle:User:index }
    methods:   [GET]

agil_profile_id:
    path:     /profil/{id}
    defaults: { _controller: AGILProfileBundle:User:showProfil }
    requirements:
        id:   \d*
    methods:   [GET]

agil_profile_edit:
    path:     /profil
    defaults: { _controller: AGILProfileBundle:User:edit }
    methods:   [POST]