agil_profile_id:
    path:     /profile/{id}
    defaults:
        _controller: AGILProfileBundle:Default:profile
    requirements:
        id:   \d+

agil_profile_delete:
    path:     /profile/delete
    defaults:
        _controller: AGILProfileBundle:Default:delete