agil_profile:
    path:     /profile
    defaults: { _controller: AGILProfileBundle:Default:index }
    methods:   [GET]

agil_profile_id:
    path:     /profile/{id}
    defaults: { _controller: AGILProfileBundle:Default:showProfile }
    requirements:
        id:   \d+
    methods:   [GET]

agil_profile_edit:
    path:     /profile/edit
    defaults: { _controller: AGILProfileBundle:Default:edit }
    methods:   [GET]