agil_profile:
    path:     /profile
    defaults: { _controller: AGILProfileBundle:Default:index }
    methods:   [GET]

agil_profile_id:
    path:     /profile/{id}
    defaults: { _controller: AGILProfileBundle:Default:showProfil }
    requirements:
        id:   \d*
    methods:   [GET]

agil_profile_edit:
    path:     /profile
    defaults: { _controller: AGILProfileBundle:Default:edit }
    methods:   [POST]