services:
    agil_profile.eventsML:
        class: AGIL\ProfileBundle\EventListener\EventsListener
        arguments: [@mailer]
        tags:
            - {name: doctrine.event_listener, event: postPersist}