agil_default_homepage:
    path: /
    defaults: { _controller: AGILDefaultBundle:Default:index }

agil_tags_search:
    path : /tags/search
    defaults: { _controller: AGILDefaultBundle:Tag:search }
