agil_default_homepage:
    path: /
    defaults: { _controller: AGILDefaultBundle:Default:index }

agil_tags_search:
    path : /tags/search
    defaults: { _controller: AGILDefaultBundle:Tag:search }

flo_tag_test:
    path: /tags/test
    defaults: { _controller: AGILDefaultBundle:Tag:testFunc }