services:
#    agil_default.example:
#        class: AGIL\DefaultBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    agil_default.tags:
        class: AGIL\DefaultBundle\TagService\Tags
        arguments: [doctrine.orm.entity_manager]