agil_search_homepage:
    path:     /
    defaults:
        _controller: AGILSearchBundle:Default:search

agil_search_test:
    path:     /test
    defaults:
        _controller: AGILSearchBundle:Default:test
        _method: GET